###
GET http://localhost:3001/api/persons/


###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Andrea Talberson",
    "number": "827-29038-20938"
}

###
DELETE http://localhost:3001/api/persons/malformedid